# Generated by Django 5.0.6 on 2024-07-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('fileuploadno', models.AutoField(primary_key=True, serialize=False)),
                ('fileuploadname', models.CharField(max_length=25)),
                ('fileupload', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
